---
packages:
  - packages/*
catalog:
  '@iconify-json/ant-design': ^1.2.5
  '@iconify-json/el': ^1.2.1
  '@iconify-json/ep': ^1.2.2
  '@iconify-json/fa': ^1.2.1
  '@iconify-json/mdi': ^1.2.3
  '@lincy/async-validation': ^1.3.0
  '@lincy/eslint-config': ^5.5.0
  '@lincy/stylelint-config': ^2.0.1
  '@lincy/unocss-base-config': ^2.2.1
  '@lincy/utils': ^0.6.2
  '@types/node': ^22.13.10
  '@types/nprogress': ^0.2.3
  '@types/throttle-debounce': ^5.0.2
  '@unocss/eslint-plugin': ^65.5.0
  '@vitejs/plugin-vue': ^5.2.1
  '@vitejs/plugin-vue-jsx': ^4.1.1
  '@vue-macros/volar': ^0.30.15
  '@vue/compiler-sfc': ^3.5.13
  '@vueuse/core': ^13.0.0
  axios: ^1.8.2
  cross-env: ^7.0.3
  element-plus: ^2.9.6
  eslint: ^9.22.0
  eslint-plugin-format: ^1.0.1
  lint-staged: ^15.4.3
  mockjs: ^1.1.0
  nprogress: ^0.2.0
  pinia: ^3.0.1
  sass: ^1.85.1
  simple-git-hooks: ^2.11.1
  throttle-debounce: ^5.0.2
  typescript: ^5.8.2
  unocss: ^65.5.0
  unplugin-auto-import: ^19.1.1
  unplugin-icons: ^22.1.0
  unplugin-vue-components: ^28.4.1
  unplugin-vue-macros: ^2.14.5
  vite: ^6.2.1
  vite-plugin-inspect: ^11.0.0
  vite-plugin-mock: ^3.0.2
  vite-plugin-progress: ^0.0.7
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.2.8
  vuex: ^4.1.0
  xlsx: ^0.18.5
